name: formkit_generator
description: "Code generation package for the FormKit library."
version: 1.0.0
homepage:

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Dependencia del paquete principal que contiene la anotación y los contratos
  formkit:
    git:
      url: https://github.com/armando-086/formkit.git
      ref: main  

  # Dependencias del generador
  analyzer: ^8.4.1
  build: ^4.0.0
  source_gen: ^4.0.0
  meta: ^1.15.0
  glob: ^2.1.3
  collection: ^1.18.0

dev_dependencies:
  # build_runner es una dependencia de desarrollo, esencial para esta división
  build_runner: ^2.10.0 
  test: ^1.26.2