name: formkit_generator
description: "Code generation package for the FormKit library."
version: 1.0.0
homepage:

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  formkit: 
    git:
      url: https://github.com/armando-086/formkit.git
      ref: main

  # Dependencias del generadoR
  analyzer: ^6.4.1
  build: ^2.4.1
  source_gen: ^1.5.0
  meta: ^1.15.0
  glob: ^2.1.3
  collection: ^1.18.0

dev_dependencies:
  # build_runner es una dependencia de desarrollo, esencial para esta divisiÃ³n
  build_runner: ^2.4.13
  test: ^1.26.2