name: formkit_generator
description: "Code generation package for the FormKit library."
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  # El generador depende del runtime (formkit)
  formkit:
    path: ../formkit

  analyzer: ^8.4.1
  build: ^4.0.0
  source_gen: ^4.0.0
  meta: ^1.15.0
  glob: ^2.1.3
  collection: ^1.18.0

dev_dependencies:
  build_runner: ^2.10.3
  test: ^1.26.2